### ISSUE TITLE
24.08beta?

### ISSUE THREAD

**Issue by vixalien** [flathub/org.freedesktop.Sdk.Extension.node20#10]
Many SDK Extensions now have a `24.08beta` version (I checked with rust), and I believe those versions are required for GNOME Runtime master.

I wonder what would be needed to publish that to `flathub-beta` and I'm willing to help.

**Comment by bbhtt** [comment]
https://buildbot.flathub.org/#/builders/6/builds/132891

https://github.com/flathub/org.freedesktop.Sdk.Extension.node20/tree/beta

I pushed it as @razzeee might've been busy.
